theme: jekyll-theme-minimal

title: Explorations in Computing
short-title: Explorations
course-number: CSC 54-144
semester: Spring
year: 2018

location: Olin 113

class-time: TTh 10:00am-11:15am

instructor: Dr. Chad Stolper

instructor-email: stolperc at southwestern.edu

instructor-office: MBH 142B

office-hours: See Moodle or office door for listed office hours. You may also make appointments, or swing by my office if my door is open.

show_downloads: false